<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/2
 * Time: 11:24
 * Comment: 基础控制器
 */
namespace app\index\controller;

use think\Controller;

class BaseController extends Controller {

    public $defaultLang = 'cn';
    public $tplName = null;
    public $webConfig = array();
    public $htmlPower = NULL;
    public $member = NULL;

    public function _initialize()
    {
        header('Content-Type:text/html;charset=utf-8');
        parent::_initialize(); // TODO: Change the autogenerated stub

        /* 获取首页导航数据 */
        $category = model('category')->where(array('is_recommend' => 1))->order('list_order desc')->limit(6)->select();

        foreach ($category as $key => $vo) {
            $navigation[$key]['cate_id'] = $vo['id'];
            $navigation[$key]['cate_name'] = $vo['cate_name'];
            $navigation[$key]['pic_path'] = $vo['pic_path'];
        }
        $this->assign("navigation", $navigation);
    }

}